# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticequeuebatch',
            name='pickled_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[('1', 'Email')], max_length=1, verbose_name='medium'),
        ),
    ]
